### ISSUE TITLE
Manger Button not showing up after trying all fixes

### ISSUE THREAD

**Issue by ThePetePandaPablo** [Comfy-Org/ComfyUI-Manager#1515]
I have tried installing each type of way and still not luck. I removed any other nodes from custom_nodes folder and button is still not showing up. How do I completly restart for scratch as it was working in the past. Is there some folder sitting somewhere on my pc stopping it from working? 

F:\Software\COMFYUI1\1\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-02-03 10:39:34.211
** Platform: Windows
** Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
** Python executable: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI
** User directory: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   2.3 seconds: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 24576 MB, total RAM 32619 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch attention
ComfyUI version: 0.3.13
[Prompt Server] web root: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\web
Traceback (most recent call last):
  File "F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2110, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 8, in <module>
    import manager_server  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 17, in <module>
    import manager_core as core
  File "F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 29, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'

Cannot import F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: No module named 'rich'

Import times for custom nodes:
   0.0 seconds: F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): F:\Software\COMFYUI1\1\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

[comfyui.log](https://github.com/user-attachments/files/18641053/comfyui.log)

**Comment by ltdrdata** [comment]
This issue is fixed already.
Please update ComfyUI-Manager to the latest version.

Goto `custom_nodes/comfyui-manger` and execute `git pull`

**Comment by ThePetePandaPablo** [comment]
https://github.com/user-attachments/assets/f23c873f-cdfd-4ab8-b050-edbcbe1dbf62

**Comment by ThePetePandaPablo** [comment]
idk its still not working, any know what update still works?

**Comment by ltdrdata** [comment]
> https://github.com/user-attachments/assets/f23c873f-cdfd-4ab8-b050-edbcbe1dbf62

![Screenshot_20250204_181941_Gallery.jpg](https://github.com/user-attachments/assets/53a179cd-28ca-46f3-85b8-b70ab0b53950)

Your ComfyUI updating is failing because of conflicts.
And your ComfyUI is very outdated version. I can see very old UI.
Goto ComfyUI dir in cmd.
And execute `git pull`

Then, error messages will indicate which files were modified.
