### ISSUE TITLE
No module named 'chardet' / 'rich' after clean installation

### ISSUE THREAD

**Issue by pto2k** [Comfy-Org/ComfyUI-Manager#1554]
fresh install of ComfyUI portable 0.3.14
(https://github.com/comfyanonymous/ComfyUI/releases/download/v0.3.14/ComfyUI_windows_portable_nvidia.7z) 

Tried ComfyUI-Manager's installation method 1 and 2 on the home page. Both failed.

Output with method 2:

> e:\Repo\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
> Failed to execute startup-script: E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\prestartup_script.py / No module named 'chardet'
> 
> Prestartup times for custom nodes:
>    0.4 seconds (PRESTARTUP FAILED): E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
> 
> Checkpoint files will always be loaded safely.
> Total VRAM 12281 MB, total RAM 65457 MB
> pytorch version: 2.6.0+cu126
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
> Using pytorch attention
> ComfyUI version: 0.3.14
> [Prompt Server] web root: e:\Repo\ComfyUI_windows_portable\ComfyUI\web
> Traceback (most recent call last):
>   File "e:\Repo\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2112, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\__init__.py", line 8, in <module>
>     import manager_server  # noqa: F401
>     ^^^^^^^^^^^^^^^^^^^^^
>   File "E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\glob\manager_server.py", line 17, in <module>
>     import manager_core as core
>   File "E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\glob\manager_core.py", line 29, in <module>
>     from rich import print
> ModuleNotFoundError: No module named 'rich'
> 
> Cannot import E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager module for custom nodes: No module named 'rich'
> 
> Import times for custom nodes:
>    0.0 seconds: E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
>    0.3 seconds (IMPORT FAILED): E:\Repo\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188

also error with method 1 is missing 'git' module.

Please help.
Thank you.

**Comment by crashbone2k** [comment]
pip install chardet ✔

![Image](https://github.com/user-attachments/assets/6a7e9364-f155-4666-a3c9-6d3e46a70652)

**Comment by mls2009** [comment]
same problem

**Comment by Timuliao** [comment]
Same problem too

**Comment by veeroo18** [comment]
same problem with git module 
1 and 2 methods fail 
ModuleNotFoundError: No module named 'git'

![Image](https://github.com/user-attachments/assets/f11c5140-f86a-4db6-be7e-d0f39329dc11)

**Comment by vojd11** [comment]
If `pip install chardet` had zero result, try `pip3 install chardet`. Don't forget activate venv

**Comment by sayimburak** [comment]
This problem is caused by the missing **chardet** and **rich** modules. For **ComfyUI portable** version, follow these steps:

1. Open the **ComfyUI folder** from the file explorer.
2. Type "**cmd**" in the address bar and press enter.
3. Paste and run these two codes: 
```
.\python_embeded\python.exe -m pip install chardet
.\python_embeded\python.exe -m pip install rich
```

**Comment by veeroo18** [comment]
I am getting same error for git, as mentioned in last comment what could be the issue
tried following 

![Image](https://github.com/user-attachments/assets/2510e665-78d6-49b4-af27-76c20c6b05da)

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by TheLastDinosaur** [comment]
Same issue, with a clean installation of comfy UI latest Version. 0.3.14.

    from rich import print
ModuleNotFoundError: No module named 'rich'

**Comment by veeroo18** [comment]
tried method 1 - git clone in custom nodes folder - 


now its giving 
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/
ERROR: Could not find a version that satisfies the requirement numpy<2 (from versions: none)
ERROR: No matching distribution found for numpy<2
[ComfyUI-Manager] Failed to restore numpy
Command '['F:\\apps\\AI\\python_embeded\\python.exe', '-m', 'pip', 'install', 'numpy<2']' returned non-zero exit status 1.

Prestartup times for custom nodes:
  33.2 seconds: F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 6144 MB, total RAM 49078 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Using pytorch attention
ComfyUI version: 0.3.14
[Prompt Server] web root: F:\apps\AI\ComfyUI\web
Traceback (most recent call last):
  File "F:\apps\AI\ComfyUI\nodes.py", line 2112, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager\__init__.py", line 8, in <module>
    import manager_server  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^
  File "F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager\glob\manager_server.py", line 13, in <module>
    import git
ModuleNotFoundError: No module named 'git'

Cannot import F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager module for custom nodes: No module named 'git'

Import times for custom nodes:
   0.0 seconds: F:\apps\AI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager

**Comment by ltdrdata** [comment]
> tried method 1 - git clone in custom nodes folder -
> 
> now its giving WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/numpy/ ERROR: Could not find a version that satisfies the requirement numpy<2 (from versions: none) ERROR: No matching distribution found for numpy<2 [ComfyUI-Manager] Failed to restore numpy Command '['F:\apps\AI\python_embeded\python.exe', '-m', 'pip', 'install', 'numpy<2']' returned non-zero exit status 1.
> 
> Prestartup times for custom nodes: 33.2 seconds: F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager
> 
> Checkpoint files will always be loaded safely. Total VRAM 6144 MB, total RAM 49078 MB pytorch version: 2.6.0+cu126 Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync Using pytorch attention ComfyUI version: 0.3.14 [Prompt Server] web root: F:\apps\AI\ComfyUI\web Traceback (most recent call last): File "F:\apps\AI\ComfyUI\nodes.py", line 2112, in load_custom_node module_spec.loader.exec_module(module) File "", line 999, in exec_module File "", line 488, in _call_with_frames_removed File "F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager__init__.py", line 8, in import manager_server # noqa: F401 ^^^^^^^^^^^^^^^^^^^^^ File "F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager\glob\manager_server.py", line 13, in import git ModuleNotFoundError: No module named 'git'
> 
> Cannot import F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager module for custom nodes: No module named 'git'
> 
> Import times for custom nodes: 0.0 seconds: F:\apps\AI\ComfyUI\custom_nodes\websocket_image_save.py 0.0 seconds (IMPORT FAILED): F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager

It seems that your network environment unstable.

This is unrelated to this issue, but try execute this.
```
F:\apps\AI\python_embeded\python.exe -m pip install "numpy<2"
```

And in a normal network environment, this method should resolve the issue.  
Originally, this should be installed automatically when ComfyUI-Manager runs.
```
F:\apps\AI\python_embeded\python.exe -m pip install -r F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager\requirements.txt
```

**Comment by TheLastDinosaur** [comment]
@ltdrdata  i have taken your latest commit related to this issue(Fixed chardet to be lazy), but still getting the same error. 
With a clean installation of ComfyUI  -> ComfyUIManager using the script 



C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)
  WARNING: The script chardetect.exe is installed in 'C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-02-16 17:27:56.495
** Platform: Windows
** Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
** Python executable: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** ComfyUI Base Folder Path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** User directory: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user
** ComfyUI-Manager config path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user\comfyui.log
  WARNING: The script f2py.exe is installed in 'C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0 -> 25.0.1
[notice] To update, run: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip

Prestartup times for custom nodes:
  19.6 seconds: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 6144 MB, total RAM 15790 MB
pytorch version: 2.6.0+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
Using pytorch attention
ComfyUI version: 0.3.14
[Prompt Server] web root: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
Traceback (most recent call last):
  File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2112, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\__init__.py", line 8, in <module>
    import manager_server  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\glob\manager_server.py", line 17, in <module>
    import manager_core as core
  File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\glob\manager_core.py", line 29, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'

Cannot import C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager module for custom nodes: No module named 'rich'

Import times for custom nodes:
   0.0 seconds: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.1 seconds (IMPORT FAILED): C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by veeroo18** [comment]
oh may be, 
but I see following error 
when tried following command 
F:\apps\AI>F:\apps\AI\python_embeded\python.exe -m pip install -r F:\apps\AI\ComfyUI\custom_nodes\comfyui-manager\requirements.txt


WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/gitpython/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/gitpython/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/gitpython/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/gitpython/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/gitpython/
ERROR: Could not find a version that satisfies the requirement GitPython (from versions: none)
ERROR: No matching distribution found for GitPython

**Comment by builder-main** [comment]
`ModuleNotFoundError: No module named 'rich'`

`python_embeded/python -m pip install rich --force-reinstall` force reinstall as it was refusing to install it and was keeping the system python ref instead.

**Comment by ltdrdata** [comment]
> `ModuleNotFoundError: No module named 'rich'`
> 
> `python_embeded/python -m pip install rich --force-reinstall` force reinstall as it was refusing to install it and was keeping the system python ref instead.

It seems that your python version doesn't support that package. What is your python version?

**Comment by ltdrdata** [comment]
> @ltdrdata  i have taken your latest commit related to this issue(Fixed chardet to be lazy), but still getting the same error. 
> With a clean installation of ComfyUI  -> ComfyUIManager using the script 
> 
> 
> 
> C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
> [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies. (GitPython)
>   WARNING: The script chardetect.exe is installed in 'C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> 
> [notice] A new release of pip is available: 25.0 -> 25.0.1
> [notice] To update, run: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2025-02-16 17:27:56.495
> ** Platform: Windows
> ** Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
> ** Python executable: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
> ** ComfyUI Path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
> ** ComfyUI Base Folder Path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
> ** User directory: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user
> ** ComfyUI-Manager config path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager\config.ini
> ** Log path: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\user\comfyui.log
>   WARNING: The script f2py.exe is installed in 'C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> 
> [notice] A new release of pip is available: 25.0 -> 25.0.1
> [notice] To update, run: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
> 
> Prestartup times for custom nodes:
>   19.6 seconds: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
> 
> Checkpoint files will always be loaded safely.
> Total VRAM 6144 MB, total RAM 15790 MB
> pytorch version: 2.6.0+cu126
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
> Using pytorch attention
> ComfyUI version: 0.3.14
> [Prompt Server] web root: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
> Traceback (most recent call last):
>   File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2112, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\__init__.py", line 8, in <module>
>     import manager_server  # noqa: F401
>     ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\glob\manager_server.py", line 17, in <module>
>     import manager_core as core
>   File "C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager\glob\manager_core.py", line 29, in <module>
>     from rich import print
> ModuleNotFoundError: No module named 'rich'
> 
> Cannot import C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager module for custom nodes: No module named 'rich'
> 
> Import times for custom nodes:
>    0.0 seconds: C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
>    0.1 seconds (IMPORT FAILED): C:\Users\psyam\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> 
> 
> 

I've added a patch that is expected to fix this issue. Update ComfyUI-Manager to v3.26.1 and test it.

**Comment by donlinglok1** [comment]
> `ModuleNotFoundError: No module named 'rich'`
> 
> `python_embeded/python -m pip install rich --force-reinstall` force reinstall as it was refusing to install it and was keeping the system python ref instead.

sorry guys, i know this issues is closed but this "--force-reinstall" acutaully save my life.

I have already try this and always return "Requirement already satisfied"
```
.\python_embeded\python.exe -m pip install chardet
.\python_embeded\python.exe -m pip install rich
```
then i try reisntall the ComfyUI-Manager, use latest version ComfyUI+ComfyUI-Manager, reinstall ComfyUI, remove all custom node, try using docker version ComfyUI, remove all python site-packages... and all didn't work.

The final soultion works for me is 
```
.\python_embeded\python.exe -m pip install chardet
.\python_embeded\python.exe -m pip install rich **--force-reinstall**
```
I think this problem happens to me because i install too many custom_node and run `update_comfyui_and_python_dependencies.bat`

Thank you @builder-main @ltdrdata

**Comment by ejamshidiasl** [comment]
i found a solution, actually i have python 3.12 installed and comfyui uses python 3.12 too. so when i installed manager, it installed rich module using my own python.exe (in path env). so i went to app/roaming/python and copied rich to comfyui python dir and now it works. **HOW TO SEPARATE THESE 2 PYTHONs?**

**Comment by ltdrdata** [comment]
> i found a solution, actually i have python 3.12 installed and comfyui uses python 3.12 too. so when i installed manager, it installed rich module using my own python.exe (in path env). so i went to app/roaming/python and copied rich to comfyui python dir and now it works. **HOW TO SEPARATE THESE 2 PYTHONs?** 

When installing dependencies with pip in Python, one thing to always keep in mind is that they must be installed in the same Python environment where ComfyUI is running.

Due to Python's nature, version conflicts between dependencies are common. 

To minimize this, it is recommended to use isolated Python environments for each application, such as venv, conda, or embedded Python.
