### ISSUE TITLE
OSError: [Errno 5] Input/output error when using network disk on RunPod causes ComfyUI to halt

### ISSUE THREAD

**Issue by dx777** [Comfy-Org/ComfyUI-Manager#1794]
When running ComfyUI on a RunPod instance with a network-mounted disk, the entire interface occasionally halts and throws repeated I/O-related exceptions. The issue seems to originate from ComfyUI-Manager during logging attempts, specifically when flushing logs to disk.

System Info
	•	Platform: RunPod
	•	Storage: Network-mounted disk
	•	Python: 3.10
	
Custom Nodes Involved:
	•	ComfyUI-Manager
	•	comfyui-deploy
	•	comfyui-impact-pack

Reproduction Steps: 
1. Set up ComfyUI on RunPod using a network disk for storage
2. Run workflows for an extended period (couple of days)
3. Error occurs intermittently during normal operation

```
Traceback (most recent call last):
  File "/workspace/ComfyUI/custom_nodes/comfyui-deploy/custom_routes.py", line 498, in comfy_deploy_run
    res = post_prompt(prompt)
  File "/workspace/ComfyUI/custom_nodes/comfyui-deploy/custom_routes.py", line 245, in post_prompt
    json_data = prompt_server.trigger_on_prompt(json_data)
  File "/workspace/ComfyUI/server.py", line 862, in trigger_on_prompt
    logging.warning("[ERROR] An error occurred during the on_prompt_handler processing")
  File "/usr/lib/python3.10/logging/__init__.py", line 2123, in warning
    root.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1489, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Manager/prestartup_script.py", line 419, in emit
    stderr_wrapper.sync_write(message+'\n', file_only=True)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-Manager/prestartup_script.py", line 341, in sync_write
    log_file.flush()
OSError: [Errno 5] Input/output error
```

**Comment by ltdrdata** [comment]
This issue is fixed.

**Comment by todochenxi** [comment]
> This issue is fixed.

The issue still persists, so I had no choice but to uninstall the manager.
