### ISSUE TITLE
The Manager menu button is missing after ComfyUI update

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [Comfy-Org/ComfyUI-Manager#328]
"Error loading extension",
  "/extensions/ComfyUI-Manager/comfyui-manager.js",
  "TypeError\nFailed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Manager/comfyui-manager.js\nTypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/ComfyUI-Manager/comfyui-manager.js\n"

**Comment by The-Great-Nothing** [comment]
Had similar issue and fixed with manually deleting and reinstalling Manager using git pull.

**Comment by ltdrdata** [comment]
The error message you provided is too incomplete to determine the cause of the error. 
And the attached error message is not a message that exists in ComfyUI. In what environment are you running it?

**Comment by Dean-ZhenYao-Wang** [comment]
> ComfyUI

The master branch of  ComfyUI。
Manually removing and reinstalling the manager using git pull did not fix。

**Comment by Dean-ZhenYao-Wang** [comment]
> 有类似的问题，并使用 git pull 手动删除和重新安装管理器进行了修复。

Manually removing and reinstalling the manager using git pull did not fix

**Comment by Dean-ZhenYao-Wang** [comment]
> The error message you provided is too incomplete to determine the cause of the error. And the attached error message is not a message that exists in ComfyUI. In what environment are you running it?

** ComfyUI startup time: 2024-01-15 20:08:06.264097
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\venv\Scripts\python.exe
** Log path: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.2 seconds: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 40664 MB
xformers version: 0.0.22.post4
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
### Loading: ComfyUI-Manager (V1.26.1)
### ComfyUI Revision: 1911 [f9e55d84] | Released on '2024-01-15'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

Import times for custom nodes:
   0.0 seconds: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.1 seconds: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\custom_nodes\comfyui-portrait-master
   0.7 seconds: D:\StabilityMatrix.Avalonia\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26154837/79d78bdd-29a0-49eb-a38a-f2a7ad057b6e)

**Comment by Dean-ZhenYao-Wang** [comment]
Manually removing and reinstalling the manager using git pull。Repeat this operation several times to solve the problem。
