### ISSUE TITLE
Comfy Manager Install Custom Nodes or Install Missing Nodes is not working

### ISSUE THREAD

**Issue by yogotatara3** [Comfy-Org/ComfyUI-Manager#332]
Hello,

somehow I have some issues with the manager. The Custom node site is not popping up neither if I press Install custom nodes nor when I select Install Missing nodes. I have a Mac M3.

Would be great if someone could help pls.

<img width="1056" alt="Bildschirmfoto 2024-01-15 um 15 52 17" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/126865816/2a652be4-44a4-4675-ad3f-afbefe6cd55a">

**Comment by TPreece101** [comment]
Probably caused by this: https://github.com/ltdrdata/ComfyUI-Manager/issues/331

**Comment by ltdrdata** [comment]
This is fixed. Retry.

**Comment by SkelegonDK** [comment]
Hi! I checked most of the other threads, and double checked the Json file in runtime, but I still get the error. I checked the Json and it's valid. I'm using cloudflare and don't get any obvious errors. localtunnel give me this. 

```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/content/drive/MyDrive/ComfyUI/server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "/content/drive/MyDrive/ComfyUI/server.py", line 102, in websocket_handler
    await ws.prepare(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_ws.py", line 152, in prepare
    payload_writer = await super().prepare(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 415, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 423, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 503, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
FETCH DATA from: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/custom-node-list.json
```

**Comment by ltdrdata** [comment]
Disable all custom nodes and test it. Then, if there are no issues, enable only the ComfyUI-Manager and test again.
Based on the current logs, it's not certain whether the issue lies with the ComfyUI-Manager.
