### ISSUE TITLE
Cannot install nodes- git_helper.py not found

### ISSUE THREAD

**Issue by Ben-Garcia-DB-Solutions** [Comfy-Org/ComfyUI-Manager#566]
I'm struggling to get ComfyUI Manager working. I'm using ComfyUI Windows Portable.

I get this error (for every node) when I attempt to install via the manager.

```
Download: git clone 'https://github.com/twri/sdxl_prompt_styler'
[!] C:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\ComfyUI_windows_portable\python_embeded\python.exe: can't open file 'C:\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu (1)\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\git_helper.py': [Errno 2] No such file or directory
```

I have tried re-downloading the latest Python, ComfyUI & ComfyUI-Manager (Using installation method 2), but have no luck.

Some googling is leading me down the line that there might be an issue with my python venv but to be honest I have absolutely no idea where to start with python environments!

**Comment by Ben-Garcia-DB-Solutions** [comment]
I think I've fixed this.

I've edited `manager_core.py` & changed line 29 to:

`git_script_path = os.path.join(comfyui_manager_path, "git_helper.py")`

from 

`git_script_path = os.path.join(custom_nodes_path, "git_helper.py")`

Changing the path seemed to get it all working happily without causing other issues.

**Comment by brbbbq** [comment]
Just came across this issue as well when trying to install a fresh version of ComfyUI. Editing the line in `manager_core.py` worked for me as well, it can be found in the folder `ComfyUI\custom_nodes\ComfyUI-Manager\glob`

I don't know if it's related, but I'm also getting this warning constantly in the terminal even after updating ComfyUI:
```###################################################################
[2024-04-15 13:09] [WARN] ComfyUI-Manager: Your ComfyUI version (Unknown)[1900-01-01] is too old. Please update to the latest version.
[2024-04-15 13:09] [WARN] The extension installation feature may not work properly in the current installed ComfyUI version on Windows environment.
[2024-04-15 13:09] ###################################################################```

**Comment by unsivilaudio** [comment]
> I think I've fixed this.
> 
> I've edited `manager_core.py` & changed line 29 to:
> 
> `git_script_path = os.path.join(comfyui_manager_path, "git_helper.py")`
> 
> from
> 
> `git_script_path = os.path.join(custom_nodes_path, "git_helper.py")`
> 
> Changing the path seemed to get it all working happily without causing other issues.

Yes looks like just a small f-up in the code, should definitely be referencing the ComfyUI-Manager path.  gg

**Comment by Graybles** [comment]
> I think I've fixed this.
> 
> I've edited `manager_core.py` & changed line 29 to:
> 
> `git_script_path = os.path.join(comfyui_manager_path, "git_helper.py")`
> 
> from
> 
> `git_script_path = os.path.join(custom_nodes_path, "git_helper.py")`
> 
> Changing the path seemed to get it all working happily without causing other issues.

This fixed it for me, Great job spotting that!

**Comment by mikheys** [comment]
> Только что столкнулся с этой проблемой при попытке установить свежую версию ComfyUI. У меня тоже сработало редактирование строки `manager_core.py`, ее можно найти в папке`ComfyUI\custom_nodes\ComfyUI-Manager\glob`
> 
> Я не знаю, связано ли это, но я также постоянно получаю это предупреждение в терминале, даже после обновления ComfyUI:
> 
> ```
> [2024-04-15 13:09] [WARN] ComfyUI-Manager: Your ComfyUI version (Unknown)[1900-01-01] is too old. Please update to the latest version.
> [2024-04-15 13:09] [WARN] The extension installation feature may not work properly in the current installed ComfyUI version on Windows environment.
> [2024-04-15 13:09] ###################################################################```
> ```

The same error and the same warning in the console.

**Comment by ltdrdata** [comment]
oh... sorry for this..

This is fixed. go to `custom_nodes/ComfyUI-Manager` dir and `git pull`

**Comment by mikheys** [comment]
I still get an error in the console when installing any extensions:

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'h5py']


###################################################################
[WARN] ComfyUI-Manager: Your ComfyUI version (Unknown)[1900-01-01] is too old. Please update to the latest version.
[WARN] The extension installation feature may not work properly in the current installed ComfyUI version on Windows environment.
###################################################################

**Comment by ltdrdata** [comment]
> [WARN] ComfyUI-Manager: Your ComfyUI version

This is patched.
Update it again.
