### ISSUE TITLE
Node updates completely broken since commit 4a1c6a8c

### ISSUE THREAD

**Issue by clayne** [Comfy-Org/ComfyUI-Manager#568]
"Update All" and "Fetch Updates" now result in the following instantaneous failures for all nodes:
```
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Manager_aux
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI_experimentsation
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\comfyui_controlnet_aux
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-MotionDiff
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Loopchain
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Video-Matting
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI_Cutoffcomfyui
Fetch error: F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
[remainder removed]
```
Here's the bisect with the problem commit:
```
clayne@sv590:/f/stablediffusion/ComfyUI/custom_nodes/ComfyUI-Manager (main=) $ git bisect start ed3403c 84de819
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[6608afe314ad993c367a5c4f27db970132bffa1c] update DB
clayne@sv590:/f/stablediffusion/ComfyUI/custom_nodes/ComfyUI-Manager ((6608afe...)|BISECTING) $ git bisect good
Bisecting: 2 revisions left to test after this (roughly 1 step)
[4fc364ba7ae84b683fa38bc6b8814383215bdcba] update DB
clayne@sv590:/f/stablediffusion/ComfyUI/custom_nodes/ComfyUI-Manager ((4fc364b...)|BISECTING) $ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[4a1c6a8cbb28093d7c4d123ba84e45a33091e64d] refactoring
clayne@sv590:/f/stablediffusion/ComfyUI/custom_nodes/ComfyUI-Manager ((4a1c6a8...)|BISECTING) $ git bisect bad
4a1c6a8cbb28093d7c4d123ba84e45a33091e64d is the first bad commit
commit 4a1c6a8cbb28093d7c4d123ba84e45a33091e64d
Author: Dr.Lt.Data <dr.lt.data@gmail.com>
Date:   Mon Apr 15 23:29:03 2024 +0900

    refactoring

 __init__.py          | 1192 ++++++++------------------------------------------
 glob/manager_core.py |  834 +++++++++++++++++++++++++++++++++++
 prestartup_script.py |    1 -
 3 files changed, 1022 insertions(+), 1005 deletions(-)
 create mode 100644 glob/manager_core.py
```
The unfortunate workaround for right now is: `git reset --hard 4a1c6a8c~1` or `git rebase -i 4a1c6a8c~1` and remove the problem commits for the time being.

**Comment by ltdrdata** [comment]
My mistake.
This is fixed, now.

**Comment by clayne** [comment]
So the fetch part of things appears to be resolved, but now I'm getting this with update all:
```
Error handling request
Traceback (most recent call last):
  File "F:\stablediffusion\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "F:\stablediffusion\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "F:\stablediffusion\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "F:\stablediffusion\ComfyUI\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "F:\stablediffusion\ComfyUI\server.py", line 53, in cors_middleware
    response = await handler(request)
  File "F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 1164, in get_notice
    markdown_content += f"<HR>ComfyUI: {comfy_ui_revision}[{comfy_ui_hash[:6]}]({comfy_ui_commit_datetime.date()})"
NameError: name 'comfy_ui_revision' is not defined
Update ComfyUI
ComfyUI update fail: name 'git' is not defined
```
This might have to do with the fact that I use a different branch than master which includes local changes. However even after switching comfyui back to master, I still get:
```
Update ComfyUI
ComfyUI update fail: name 'git' is not defined
```

**Comment by WeirdScienceX** [comment]
So how to fix it, even after doing a manual pull it still fails to update with the same message about git not being defined as above.

**Comment by DavidEBell** [comment]
I'm getting:

install: ['https://github.com/ltdrdata/ComfyUI-Manager.git']
Download: git clone 'https://github.com/ltdrdata/ComfyUI-Manager.git'
0it [00:00, ?it/s]Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Manager.git / Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --progress -- https://github.com/ltdrdata/ComfyUI-Manager.git /Volumes/Working_02d/600_AI_work/00_Pinokio_Actual/api/comfyui.git/app/custom_nodes/ComfyUI-Manager
0it [00:00, ?it/s]

**Comment by rovo79** [comment]
@clayne 
`git reset --hard 4a1c6a8c~1`

after the latest update, that was able to recover it for me.

**Comment by ltdrdata** [comment]
> So the fetch part of things appears to be resolved, but now I'm getting this with update all:
> 
> ```
> Error handling request
> Traceback (most recent call last):
>   File "F:\stablediffusion\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
>     resp = await request_handler(request)
>   File "F:\stablediffusion\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
>     resp = await handler(request)
>   File "F:\stablediffusion\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
>     return await handler(request)
>   File "F:\stablediffusion\ComfyUI\server.py", line 41, in cache_control
>     response: web.Response = await handler(request)
>   File "F:\stablediffusion\ComfyUI\server.py", line 53, in cors_middleware
>     response = await handler(request)
>   File "F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 1164, in get_notice
>     markdown_content += f"<HR>ComfyUI: {comfy_ui_revision}[{comfy_ui_hash[:6]}]({comfy_ui_commit_datetime.date()})"
> NameError: name 'comfy_ui_revision' is not defined
> Update ComfyUI
> ComfyUI update fail: name 'git' is not defined
> ```
> 
> This might have to do with the fact that I use a different branch than master which includes local changes. However even after switching comfyui back to master, I still get:
> 
> ```
> Update ComfyUI
> ComfyUI update fail: name 'git' is not defined
> ```

This is patched. 
Update it again.

**Comment by rovo79** [comment]
Thank you @ltdrdata , v2.18.4 fixed it for me. 

```
PyTorch version: 2.4.0.dev20240415
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.3
Libc version: N/A

Python version: 3.11.7 (main, Feb  8 2024, 16:24:49) [Clang 15.0.0 (clang-1500.1.0.2.5)] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.17.1
[pip3] open-clip-torch==2.24.0
[pip3] pytorch-msssim==1.0.0
[pip3] torch==2.4.0.dev20240415
[pip3] torchaudio==2.2.0.dev20240415
[pip3] torchsde==0.2.6
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.19.0.dev20240415
```

**Comment by DavidEBell** [comment]
> I'm getting:
> 
> install: ['https://github.com/ltdrdata/ComfyUI-Manager.git'] Download: git clone 'https://github.com/ltdrdata/ComfyUI-Manager.git' 0it [00:00, ?it/s]Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Manager.git / Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --progress -- https://github.com/ltdrdata/ComfyUI-Manager.git /Volumes/Working_02d/600_AI_work/00_Pinokio_Actual/api/comfyui.git/app/custom_nodes/ComfyUI-Manager 0it [00:00, ?it/s]

I'm back live and productive again
Thank you so much for your tireless work.
D
