### ISSUE TITLE
Unable to install custom nodes or use the restart feature.

### ISSUE THREAD

**Issue by WeirdScienceX** [Comfy-Org/ComfyUI-Manager#673]
I used comfyui earlier without issue.

However, when I decided to try a new workflow, I couldn't install the missing nodes. Looking at the terminal, I see the error

ERROR: The unsecure feature is disabled, restricting the installation of custom nodes. Please contact the administrator.

When trying the restart option, I see a similar message:

ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.

Is this related to comfyui manager, or have I missed up my installation somehow?

**Comment by bjornwed** [comment]
Same here, updated Comfy and all nodes and now I got this message as well...weird

**Comment by bjornwed** [comment]
ok, found it. Logic changed in the following commit for "disable_unsecure_features" : https://github.com/ltdrdata/ComfyUI-Manager/commit/40afa92f51127cac6024e70e7da7449bb35dc772

to fix it, simply update to latest fixed version, no need to change config.ini 

~~go into custom_nodes/ComfyUI-Manager and edit config.ini.
set disable_unsecure_features = True

If you for some reason you don't have the above setting in the config.ini you can add it or rename config.ini to config.ini_ to have it recreated, but then make sure to change it from "False" to "True".~~

**Comment by ltdrdata** [comment]
This was my fault. Update to latest version (v2.23.2)
and keep it 
```
disable_unsecure_features = False
```

**Comment by yw-2020** [comment]
after update all and restart, it says:
ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.

**Comment by ltdrdata** [comment]
> after update all and restart, it says: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.

What is your ComfyUI-Manager version and what is the content in the `ComfyUI-Manager/config.ini`

**Comment by yw-2020** [comment]
> > after update all and restart, it says: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.
> 
> What is your ComfyUI-Manager version and what is the content in the `ComfyUI-Manager/config.ini`

The latest version, and this is config.ini:
[default]
preview_method = none
badge_mode = none
git_exe = 
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
share_option = all
bypass_ssl = False
file_logging = True
default_ui = none
component_policy = workflow
double_click_policy = copy-all
windows_selector_event_loop_policy = False
model_download_by_agent = False
downgrade_blacklist = 
disable_unsecure_features = False

**Comment by yw-2020** [comment]
> > after update all and restart, it says: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.
> 
> What is your ComfyUI-Manager version and what is the content in the `ComfyUI-Manager/config.ini`

I conducted a test where I first deleted ComfyUI-Manager and then redownloaded and ran it, and it worked normally. However, after that, it became unusable again. Whether I restart or download other nodes through ComfyUI-Manager, it does not work properly. It can only run normally once, and then it starts to give an error:
ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.

**Comment by ltdrdata** [comment]
> > > after update all and restart, it says: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.
> > 
> > 
> > What is your ComfyUI-Manager version and what is the content in the `ComfyUI-Manager/config.ini`
> 
> I conducted a test where I first deleted ComfyUI-Manager and then redownloaded and ran it, and it worked normally. However, after that, it became unusable again. Whether I restart or download other nodes through ComfyUI-Manager, it does not work properly. It can only run normally once, and then it starts to give an error: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.

Finally... I found the real reason.... 
Update it again. Now it is resolved...

**Comment by yw-2020** [comment]
> > > > after update all and restart, it says: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.
> > > 
> > > 
> > > What is your ComfyUI-Manager version and what is the content in the `ComfyUI-Manager/config.ini`
> > 
> > 
> > I conducted a test where I first deleted ComfyUI-Manager and then redownloaded and ran it, and it worked normally. However, after that, it became unusable again. Whether I restart or download other nodes through ComfyUI-Manager, it does not work properly. It can only run normally once, and then it starts to give an error: ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator.
> 
> Finally... I found the real reason.... Update it again. Now it is resolved...

Thanks a lot, it worked!

**Comment by kubilaykilinc** [comment]
I am still getting this error. "install failed:". I can't install any new custom node. 

And i did all fixes. But i am still getting this error "ERROR: The unsecure feature is disabled, restricting the reboot feature. Please contact the administrator."

**Comment by kubilaykilinc** [comment]
I updated last version comfyui manager 2.32.3 and i did "disable_unsecure_features = False" in config.ini 
Everything is fine now.

**Comment by rizlas** [comment]
Still getting this error. Why `disable_unsecure_features` default is False?
Anyway I'm getting the error with both values.

Ini file:

```ini
[default]
preview_method = none
badge_mode = none
git_exe = 
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
share_option = all
bypass_ssl = False
file_logging = True
default_ui = none
component_policy = workflow
double_click_policy = copy-all
windows_selector_event_loop_policy = False
model_download_by_agent = False
downgrade_blacklist = 
disable_unsecure_features = False
```

Message:

```
Your ComfyUI is too OUTDATED!!!
Keywords: UnsecureFeature 
 
[UnsecureFeature] In a specific version of ComfyUI-Manager (v2.23 to v2.23.5), the update fails and displays the message 'ERROR: The unsecure feature is disabled, restricting the remove feature. Please contact the administrator.' Please go to the custom_nodes/ComfyUI-Manager directory and execute a git pull to update it.
  
ComfyUI: Unknown[-](1900-01-01)
Manager: V2.32.6
```

**Comment by ltdrdata** [comment]
> Still getting this error. Why `disable_unsecure_features` default is False? Anyway I'm getting the error with both values.
> 
> Ini file:
> 
> ```ini
> [default]
> preview_method = none
> badge_mode = none
> git_exe = 
> channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
> share_option = all
> bypass_ssl = False
> file_logging = True
> default_ui = none
> component_policy = workflow
> double_click_policy = copy-all
> windows_selector_event_loop_policy = False
> model_download_by_agent = False
> downgrade_blacklist = 
> disable_unsecure_features = False
> ```
> 
> Message:
> 
> ```
> Your ComfyUI is too OUTDATED!!!
> Keywords: UnsecureFeature 
>  
> [UnsecureFeature] In a specific version of ComfyUI-Manager (v2.23 to v2.23.5), the update fails and displays the message 'ERROR: The unsecure feature is disabled, restricting the remove feature. Please contact the administrator.' Please go to the custom_nodes/ComfyUI-Manager directory and execute a git pull to update it.
>   
> ComfyUI: Unknown[-](1900-01-01)
> Manager: V2.32.6
> ```

disable_unsecure_features blocks installation feature of custom nodes and dependencies.

goto ComfyUI dir and execute `git status` 
What is displayed?

**Comment by rizlas** [comment]
```
comfyui/custom_nodes/ComfyUI-Manager# git status
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
```

**Comment by ltdrdata** [comment]
> ```
> comfyui/custom_nodes/ComfyUI-Manager# git status
> On branch main
> Your branch is up to date with 'origin/main'.
> nothing to commit, working tree clean
> ```

I meant ComfyUI dir not the ComfyUI-Manager dir.

**Comment by WeirdScienceX** [comment]
I can confirm, the issue is now resolved

**Comment by rizlas** [comment]
I'm running comfyui with docker and removed .git folder, but here is my current version and revision. Made an update since my last message.

`ComfyUI: 2178[ece5ac](2024-05-12)`

**Comment by ltdrdata** [comment]
> I'm running comfyui with docker and removed .git folder, but here is my current version and revision. Made an update since my last message.
> 
> `ComfyUI: 2178[ece5ac](2024-05-12)`

The version management of ComfyUI-Manager is handled by git. If you have deleted the .git path, it is normal that it is not recognized.

**Comment by rizlas** [comment]
I have deleted ComfyUI git folder not ComfyUI-Manager one.

> I meant ComfyUI dir not the ComfyUI-Manager dir.
> goto ComfyUI dir and execute git status

You asked me about ComfyUI.

**Comment by rizlas** [comment]
I have deleted ComfyUI `.git` folder not ComfyUI-Manager one.
Anyway I've restored it.

> I meant ComfyUI dir not the ComfyUI-Manager dir.
> goto ComfyUI dir and execute git status

Here you go

```bash
comfyui@63c418db3672:/app$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    custom_nodes/example_node.py.example
	deleted:    custom_nodes/websocket_image_save.py
	deleted:    input/example.png
	deleted:    models/checkpoints/put_checkpoints_here
	deleted:    models/clip/put_clip_or_text_encoder_models_here
	deleted:    models/clip_vision/put_clip_vision_models_here
	deleted:    models/configs/anything_v3.yaml
	deleted:    models/configs/v1-inference.yaml
	deleted:    models/configs/v1-inference_clip_skip_2.yaml
	deleted:    models/configs/v1-inference_clip_skip_2_fp16.yaml
	deleted:    models/configs/v1-inference_fp16.yaml
	deleted:    models/configs/v1-inpainting-inference.yaml
	deleted:    models/configs/v2-inference-v.yaml
	deleted:    models/configs/v2-inference-v_fp32.yaml
	deleted:    models/configs/v2-inference.yaml
	deleted:    models/configs/v2-inference_fp32.yaml
	deleted:    models/configs/v2-inpainting-inference.yaml
	deleted:    models/controlnet/put_controlnets_and_t2i_here
	deleted:    models/diffusers/put_diffusers_models_here
	deleted:    models/embeddings/put_embeddings_or_textual_inversion_concepts_here
	deleted:    models/gligen/put_gligen_models_here
	deleted:    models/hypernetworks/put_hypernetworks_here
	deleted:    models/loras/put_loras_here
	deleted:    models/photomaker/put_photomaker_models_here
	deleted:    models/style_models/put_t2i_style_model_here
	deleted:    models/unet/put_unet_files_here
	deleted:    models/upscale_models/put_esrgan_and_other_upscale_models_here
	deleted:    models/vae/put_vae_here
	deleted:    models/vae_approx/put_taesd_encoder_pth_and_taesd_decoder_pth_here
	deleted:    output/_output_images_will_be_put_here

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.cache/
	Dockerfile
	comfyui_8188.log
	custom_venv/

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by ltdrdata** [comment]
> I have deleted ComfyUI `.git` folder not ComfyUI-Manager one. Anyway I've restored it.
> 
> > I meant ComfyUI dir not the ComfyUI-Manager dir.
> > goto ComfyUI dir and execute git status
> 
> Here you go
> 
> ```shell
> comfyui@63c418db3672:/app$ git status
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	deleted:    custom_nodes/example_node.py.example
> 	deleted:    custom_nodes/websocket_image_save.py
> 	deleted:    input/example.png
> 	deleted:    models/checkpoints/put_checkpoints_here
> 	deleted:    models/clip/put_clip_or_text_encoder_models_here
> 	deleted:    models/clip_vision/put_clip_vision_models_here
> 	deleted:    models/configs/anything_v3.yaml
> 	deleted:    models/configs/v1-inference.yaml
> 	deleted:    models/configs/v1-inference_clip_skip_2.yaml
> 	deleted:    models/configs/v1-inference_clip_skip_2_fp16.yaml
> 	deleted:    models/configs/v1-inference_fp16.yaml
> 	deleted:    models/configs/v1-inpainting-inference.yaml
> 	deleted:    models/configs/v2-inference-v.yaml
> 	deleted:    models/configs/v2-inference-v_fp32.yaml
> 	deleted:    models/configs/v2-inference.yaml
> 	deleted:    models/configs/v2-inference_fp32.yaml
> 	deleted:    models/configs/v2-inpainting-inference.yaml
> 	deleted:    models/controlnet/put_controlnets_and_t2i_here
> 	deleted:    models/diffusers/put_diffusers_models_here
> 	deleted:    models/embeddings/put_embeddings_or_textual_inversion_concepts_here
> 	deleted:    models/gligen/put_gligen_models_here
> 	deleted:    models/hypernetworks/put_hypernetworks_here
> 	deleted:    models/loras/put_loras_here
> 	deleted:    models/photomaker/put_photomaker_models_here
> 	deleted:    models/style_models/put_t2i_style_model_here
> 	deleted:    models/unet/put_unet_files_here
> 	deleted:    models/upscale_models/put_esrgan_and_other_upscale_models_here
> 	deleted:    models/vae/put_vae_here
> 	deleted:    models/vae_approx/put_taesd_encoder_pth_and_taesd_decoder_pth_here
> 	deleted:    output/_output_images_will_be_put_here
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	.cache/
> 	Dockerfile
> 	comfyui_8188.log
> 	custom_venv/
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> ```


The .git folders for ComfyUI and all custom nodes must be preserved.
Custom nodes or ComfyUI without a .git folder are no longer under the Manager's management.

**Comment by rizlas** [comment]
I have all .git folder now, but still

![immagine](https://github.com/ltdrdata/ComfyUI-Manager/assets/8522635/f5954384-4250-43db-ae47-cbcca8bf76d0)
![immagine](https://github.com/ltdrdata/ComfyUI-Manager/assets/8522635/21724c3f-13f4-4b9c-b7d9-70b6882157bc)

**Comment by ltdrdata** [comment]
> I have all .git folder now, but still
> 
> ![immagine](https://private-user-images.githubusercontent.com/8522635/330123307-f5954384-4250-43db-ae47-cbcca8bf76d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTYxNjYsIm5iZiI6MTcxNTYxNTg2NiwicGF0aCI6Ii84NTIyNjM1LzMzMDEyMzMwNy1mNTk1NDM4NC00MjUwLTQzZGItYWU0Ny1jYmNjYThiZjc2ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTU1NzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI3ZDNhZmM4MjQ5NDM0NDY5MzNiODI2Yjc3NWQ5MDBlMWMwODViMjc3NmYwMjlmMDJlZmQwMDlhZmRjZDg3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dQhqZFIiwa6GAjDwFMtQ0K4uHMvaqUrxq2qzA97qJzo) ![immagine](https://private-user-images.githubusercontent.com/8522635/330123433-21724c3f-13f4-4b9c-b7d9-70b6882157bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTYxNjYsIm5iZiI6MTcxNTYxNTg2NiwicGF0aCI6Ii84NTIyNjM1LzMzMDEyMzQzMy0yMTcyNGMzZi0xM2Y0LTRiOWMtYjdkOS03MGI2ODgyMTU3YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTU1NzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYwNDk0MmI0OTI2ZTAwZDExNWJhYmEzYWJkYTI1ZjZkNzlkOGJmMjFhNmZhNzg2NmQ3ZjRjZjBmMjI3ZTI5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0cecK-Bie74D-RxwHJzLtD1HKXXyvbi6fUVoW2zLGVc)

That is a news board. That isn't meaning your state is invalid.

**Comment by rizlas** [comment]
Really sorry about it, didn't catch >_>
